# Change these first
owner: wrktech # Your GitHub organization or username, where this repository lives
repo: status-page-skillpack # The name of this repository

sites:
  - name: SkillPack
    url: https://portal.skillpack.io/health
    __dangerous__body_down: "Down"
    __dangerous__body_degraded: "Degraded"

status-website:
  cname: status.skillpack.io
  logoUrl: https://portal.skillpack.io/static/logo/skillpack_logo_primary.png
  name: Skillpack
  #introTitle: "**Wrk** is the open-source uptime monitor and status page, powered entirely by GitHub."
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: SkillPack Portal
      href: https://portal.skillpack.io/
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
